/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Texel, Inc. (https://sketchfab.com/texel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/boxer-84767168720948b38728ff78ee6f6090
title: Boxer
*/

import React, { useEffect, useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Boxe(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('assets/boxe/boxe.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.Animation.play();
  })
  return (
    <group ref={group} {...props} dispose={null} scale={1.7} position={[-0.7,-1.7,0]}> 
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="4b2186372b25433e9727058185337a36fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="RootNode_1" scale={0.01}>
                  <group name="Object_10">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_13" geometry={nodes.Object_13.geometry} material={materials.MHeadMat0} skeleton={nodes.Object_13.skeleton} />
                    <skinnedMesh name="Object_15" geometry={nodes.Object_15.geometry} material={materials.GlovesMat0} skeleton={nodes.Object_15.skeleton} />
                    <skinnedMesh name="Object_17" geometry={nodes.Object_17.geometry} material={materials.MBodyMat0} skeleton={nodes.Object_17.skeleton} />
                    <skinnedMesh name="Object_19" geometry={nodes.Object_19.geometry} material={materials.ShoesMat0} skeleton={nodes.Object_19.skeleton} />
                    <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.PantsMat0} skeleton={nodes.Object_21.skeleton} />
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/boxe.glb')
