/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Dr.Ahmed Talha (https://sketchfab.com/dr.ahmed)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/footballer-cf9d849a4ec246c49133bba5bd25391f
title: Footballer
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export function Football(props) {
  const { nodes, materials } = useGLTF('assets/football/football.glb')
  const player = useRef()
  useFrame(({clock}) =>{
    player.current.rotation.y = clock.getElapsedTime()
    
  })
  return (
    <group ref={player} {...props} dispose={null} scale={0.03} position={[-2,-4,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <primitive object={nodes._rootJoint} />
          <skinnedMesh geometry={nodes.Object_5.geometry} material={materials.Face} skeleton={nodes.Object_5.skeleton} />
          <skinnedMesh geometry={nodes.Object_6.geometry} material={materials.Lips} skeleton={nodes.Object_6.skeleton} />
          <skinnedMesh geometry={nodes.Object_7.geometry} material={materials.Teeth} skeleton={nodes.Object_7.skeleton} />
          <skinnedMesh geometry={nodes.Object_8.geometry} material={materials.Torso} skeleton={nodes.Object_8.skeleton} />
          <skinnedMesh geometry={nodes.Object_9.geometry} material={materials.Ears} skeleton={nodes.Object_9.skeleton} />
          <skinnedMesh geometry={nodes.Object_10.geometry} material={materials.Legs} skeleton={nodes.Object_10.skeleton} />
          <skinnedMesh geometry={nodes.Object_11.geometry} material={materials.EyeSocket} skeleton={nodes.Object_11.skeleton} />
          <skinnedMesh geometry={nodes.Object_12.geometry} material={materials.Mouth} skeleton={nodes.Object_12.skeleton} />
          <skinnedMesh geometry={nodes.Object_13.geometry} material={materials.Arms} skeleton={nodes.Object_13.skeleton} />
          <skinnedMesh geometry={nodes.Object_14.geometry} material={materials.Pupils} skeleton={nodes.Object_14.skeleton} />
          <skinnedMesh geometry={nodes.Object_15.geometry} material={materials.EyeMoisture} skeleton={nodes.Object_15.skeleton} />
          <skinnedMesh geometry={nodes.Object_16.geometry} material={materials.Fingernails} skeleton={nodes.Object_16.skeleton} />
          <skinnedMesh geometry={nodes.Object_17.geometry} material={materials.Cornea} skeleton={nodes.Object_17.skeleton} />
          <skinnedMesh geometry={nodes.Object_18.geometry} material={materials.Irises} skeleton={nodes.Object_18.skeleton} />
          <skinnedMesh geometry={nodes.Object_19.geometry} material={materials.Sclera} skeleton={nodes.Object_19.skeleton} />
          <skinnedMesh geometry={nodes.Object_20.geometry} material={materials.Toenails} skeleton={nodes.Object_20.skeleton} />
          <skinnedMesh geometry={nodes.Object_21.geometry} material={materials.Eyelashes} skeleton={nodes.Object_21.skeleton} />
          <skinnedMesh geometry={nodes.Object_22.geometry} material={materials.EyeMoisture_0} skeleton={nodes.Object_22.skeleton} />
          <skinnedMesh geometry={nodes.Object_23.geometry} material={materials.shirt} skeleton={nodes.Object_23.skeleton} />
          <skinnedMesh geometry={nodes.Object_24.geometry} material={materials.collar} skeleton={nodes.Object_24.skeleton} />
          <skinnedMesh geometry={nodes.Object_25.geometry} material={materials.sleeves} skeleton={nodes.Object_25.skeleton} />
          <skinnedMesh geometry={nodes.Object_26.geometry} material={materials.pants} skeleton={nodes.Object_26.skeleton} />
          <skinnedMesh geometry={nodes.Object_27.geometry} material={materials.trim} skeleton={nodes.Object_27.skeleton} />
          <skinnedMesh geometry={nodes.Object_28.geometry} material={materials.socks} skeleton={nodes.Object_28.skeleton} />
          <skinnedMesh geometry={nodes.Object_29.geometry} material={materials.straps} skeleton={nodes.Object_29.skeleton} />
          <skinnedMesh geometry={nodes.Object_30.geometry} material={materials.shoe} skeleton={nodes.Object_30.skeleton} />
          <skinnedMesh geometry={nodes.Object_31.geometry} material={materials.sole} skeleton={nodes.Object_31.skeleton} />
          <skinnedMesh geometry={nodes.Object_32.geometry} material={materials.spikes} skeleton={nodes.Object_32.skeleton} />
          <skinnedMesh geometry={nodes.Object_33.geometry} material={materials.tongue} skeleton={nodes.Object_33.skeleton} />
          <skinnedMesh geometry={nodes.Object_34.geometry} material={materials.trim_0} skeleton={nodes.Object_34.skeleton} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/football.glb')
