/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Lucia Criscuolo (https://sketchfab.com/Neruth)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/golden-ticket-e4672f8d1fea41829301a93a4e67bd48
title: Golden Ticket
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Goldenticket(props) {
  const { nodes, materials } = useGLTF('assets/goldenticket/goldenticket.glb')
  return (
    <group {...props} dispose={null} scale={50}> 
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh geometry={nodes.GOLDEN_TICKET_blinn1_0.geometry} material={materials.blinn1} />
          <mesh geometry={nodes.GOLDEN_TICKET_blinn2_0.geometry} material={materials.blinn2} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/goldenticket.glb')
