/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: gozdemrl (https://sketchfab.com/gozdemrl)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tennis-racket-ball-578410b9289f493cb634903cb5207a33
title: Tennis Racket & Ball
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export function Racket(props) {
  const { nodes, materials } = useGLTF('assets/tennis/racket.glb')
  const racket = useRef()
  useFrame(({clock}) =>{
    racket.current.rotation.y = clock.getElapsedTime() *2
  })
  return (
    <group ref={racket} {...props} dispose={null} scale={0.005} position={[-3,-7,0]}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group position={[79.83, 1250.62, 244.4]} rotation={[-1.41, -0.93, 0.76]} scale={100}>
            <mesh geometry={nodes.defaultMaterial.geometry} material={materials.material_3} />
          </group>
          <group position={[-111.63, 1259.41, 54.05]} rotation={[0, 0.45, 0.61]} scale={[206.14, 285.67, 206.14]}>
            <mesh geometry={nodes.defaultMaterial_1.geometry} material={materials.material_2} />
          </group>
          <group position={[273.24, 649.28, -132.31]} rotation={[-1.27, -0.54, 0.53]} scale={35.28}>
            <mesh geometry={nodes.defaultMaterial_2.geometry} material={materials.material} />
          </group>
          <group position={[-161.61, 1338.66, 78.26]} rotation={[0, 0.45, 0.61]} scale={[213.41, 213.41, 24.92]}>
            <mesh geometry={nodes.defaultMaterial_3.geometry} material={materials.base} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/racket.glb')
