/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: TetsuoTetsuo (https://sketchfab.com/TetsuoTetsuo)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/soccer-stadium-11-scale-b21e4e42c9b3487eaa9595dfa5f9af6b
title: Soccer Stadium 1:1 Scale
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export function Stadium1(props) {
  const { nodes, materials } = useGLTF('assets/stadium1/stadium1.glb')
  const stad = useRef()
  useFrame(({clock}) =>{
    stad.current.rotation.y = clock.getElapsedTime() * 0.3
  })
  return (
    <group {...props} dispose={null} scale={0.0012} ref={stad}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={[45, 0.13, 60]}>
            <mesh geometry={nodes.Cube_Material_0.geometry} material={materials.Material} />
            <mesh geometry={nodes.Cube_Material001_0.geometry} material={materials['Material.001']} />
          </group>
          <group scale={[3.18, 0.12, 60]}>
            <mesh geometry={nodes.Cube002_Material_0.geometry} material={materials.Material} />
          </group>
          <group scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube003_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0, -1186.37]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube001_Material_0.geometry} material={materials.Material} />
          </group>
          <group scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube004_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0, 6.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={[3.18, 0.12, 60]}>
            <mesh geometry={nodes.Cube005_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0, 6.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube006_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0, 1193.19]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube007_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 0, 6.82]} rotation={[-Math.PI, 0, -Math.PI]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube008_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[7.67, 0, 2232.8]} rotation={[0, Math.PI / 2, 0]} scale={[3.18, 0.12, 44.78]}>
            <mesh geometry={nodes.Cube011_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-1485.6, 0, 2232.8]} rotation={[0, Math.PI / 2, 0]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube012_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-1184.48, 0, 2232.8]} rotation={[0, Math.PI / 2, 0]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube013_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-262.42, 0, 2232.8]} rotation={[0, Math.PI / 2, 0]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube014_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-7.26, 0, -2284.75]} rotation={[0, -Math.PI / 2, 0]} scale={[3.18, 0.12, 44.78]}>
            <mesh geometry={nodes.Cube015_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[1486.01, 0, -2284.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube016_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[1184.89, 0, -2284.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube017_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[262.83, 0, -2284.75]} rotation={[0, -Math.PI / 2, 0]} scale={[0.48, 0.09, 0.46]}>
            <mesh geometry={nodes.Cube018_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[5652.18, 522.81, 7780.04]} scale={[11.51, 5.28, 17.73]}>
            <mesh geometry={nodes.Cube020_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[4408.77, 5861.16, 5863.74]} rotation={[2.57, -0.7, 2.75]} scale={[7.06, 3.91, 0.44]}>
            <mesh geometry={nodes.Cube024_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-7037.91, 2005.38, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 12.47, 60.33]}>
            <mesh geometry={nodes.Cube029_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-22.66, 295.25, 5934.91]} rotation={[0, 0, -Math.PI / 2]} scale={[0.1, 0.39, 0.1]}>
            <mesh geometry={nodes.Cylinder003_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-16.04, 113.85, 6080.9]} scale={[3.6, 1, 1]}>
            <mesh geometry={nodes.Cube031_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-22.1, 14.62, 6180.05]}>
            <mesh geometry={nodes.Plane_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-17.87, 295.25, -5953.42]} rotation={[Math.PI, 0, Math.PI / 2]} scale={[0.1, 0.39, 0.1]}>
            <mesh geometry={nodes.Cylinder001_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-24.49, 113.85, -6099.41]} rotation={[-Math.PI, 0, -Math.PI]} scale={[3.6, 1, 1]}>
            <mesh geometry={nodes.Cube033_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-18.44, 14.62, -6198.56]} rotation={[-Math.PI, 0, -Math.PI]}>
            <mesh geometry={nodes.Plane002_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[6912.2, 2005.38, 0]} rotation={[Math.PI, 0, 0]} scale={[-1, 12.47, 60.33]}>
            <mesh geometry={nodes.Cube032_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-27.28, 2005.38, -9254.2]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-1, 12.47, 45.09]}>
            <mesh geometry={nodes.Low_End_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[6910.29, 2005.38, 0]} rotation={[-Math.PI, 0, 0]} scale={[-1, 12.47, 60.33]}>
            <mesh geometry={nodes.Cube030_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-27.28, 2005.38, 9070.28]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-1, 12.47, 45.09]}>
            <mesh geometry={nodes.High_End_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-13.48, 2005.38, -9264.4]} rotation={[Math.PI, -Math.PI / 2, 0]} scale={[-1, 12.47, 44.85]}>
            <mesh geometry={nodes.Cube038_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-7053.38, 2005.38, 0]} rotation={[0, 0, -Math.PI]} scale={[-1, 12.47, 58.83]}>
            <mesh geometry={nodes.Cube039_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-13.48, 2005.38, 9086.79]} rotation={[Math.PI, Math.PI / 2, 0]} scale={[-1, 12.47, 44.85]}>
            <mesh geometry={nodes.Cube035_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[5928.13, 4781.95, -7536.84]} rotation={[0, -0.24, 0]} scale={[0.67, 25.64, 0.79]}>
            <mesh geometry={nodes.Cube021_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[5748.73, 7552.7, -7347.11]} rotation={[0.59, -0.73, 0.42]} scale={[7.03, 3.89, 0.44]}>
            <mesh geometry={nodes.Cube022_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[2732.5, -7.69, -4174.93]} rotation={[-Math.PI, -0.74, -Math.PI]} scale={[2.15, 0.12, 25.2]}>
            <mesh geometry={nodes.Corner_Seats_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-6135.36, 4829.72, 7242.86]} rotation={[-Math.PI, 0.24, -Math.PI]} scale={[0.67, 25.64, 0.79]}>
            <mesh geometry={nodes.Cube027_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-5955.96, 7600.47, 7053.12]} rotation={[2.55, 0.73, -2.72]} scale={[7.03, 3.89, 0.44]}>
            <mesh geometry={nodes.Cube028_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-2820.53, -7.69, 4031.9]} rotation={[0, 0.74, 0]} scale={[2.15, 0.12, 25.2]}>
            <mesh geometry={nodes.Corner_Seats_Red001_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 162.09, 6425.51]} rotation={[-Math.PI, 0, Math.PI]} scale={[-42.66, 1.54, 0.19]}>
            <mesh geometry={nodes.Cube023_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[0, 162.09, -6428.47]} rotation={[-Math.PI, 0, Math.PI]} scale={[-42.66, 1.54, 0.19]}>
            <mesh geometry={nodes.Cube041_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[4294.48, 106.64, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 60.08]}>
            <mesh geometry={nodes.Billboard_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-4220.88, 106.64, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[1, 1, 60.08]}>
            <mesh geometry={nodes.Billboard_2_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[5170.5, 757.38, -7998.32]} rotation={[-Math.PI, -0.74, -Math.PI]} scale={[0.34, 0.09, 0.46]}>
            <mesh geometry={nodes.Corner_Seats_Red_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-5154.58, 757.38, 7965.6]} rotation={[0, 0.74, 0]} scale={[0.34, 0.09, 0.46]}>
            <mesh geometry={nodes.Corner_Seats001_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-3866.06, 108.26, -5973.99]} rotation={[0, 0.6, 0]}>
            <mesh geometry={nodes.Cylinder_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[3870.51, 108.26, -5973.99]} rotation={[-Math.PI, 0.58, -Math.PI]}>
            <mesh geometry={nodes.Cylinder002_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-3866.06, 108.26, 5955.89]} rotation={[0, 0.6, 0]}>
            <mesh geometry={nodes.Cylinder004_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[3870.51, 108.26, 5955.89]} rotation={[-Math.PI, 0.58, -Math.PI]}>
            <mesh geometry={nodes.Cylinder005_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-6019.19, 522.81, -7786.55]} rotation={[-Math.PI, 0, -Math.PI]} scale={[15.22, 5.28, 17.73]}>
            <mesh geometry={nodes.Cube037_Material_0.geometry} material={materials.Material} />
          </group>
          <group position={[-4363.86, 5861.16, -5858.06]} rotation={[0.57, 0.7, -0.39]} scale={[7.06, 3.91, 0.44]}>
            <mesh geometry={nodes.Cube040_Material_0.geometry} material={materials.Material} />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/stadium1.glb')
