/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: rosaliarenda (https://sketchfab.com/rosaliarenda)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/tennista-palla-92de6dd75f7648c1bfaae8a8b91e2624
title: tennista +palla
*/

import React, { useRef , useEffect, UseUpdate} from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { useFrame } from '@react-three/fiber'
export function Tennisplayer(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('assets/tennisplayer/tennisplayer.glb')
  const { actions } = useAnimations(animations, group)
  useEffect(() => {
    actions.Scene.play();
  })


  return (
    <group ref={group} {...props} dispose={null} scale={0.0045} position={[-5,-4,0]} >
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="15ab0a3ccd0a478da1d6c880ea46f7c3fbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Game_engine" position={[60.82, -92.45, 20.78]} rotation={[2.28, -1.39, 2.25]} scale={10}>
                  <group name="Object_9">
                    <primitive object={nodes._rootJoint} />
                    <skinnedMesh name="Object_78" geometry={nodes.Object_78.geometry} material={materials.sport_briefs01} skeleton={nodes.Object_78.skeleton} />
                    <skinnedMesh name="Object_80" geometry={nodes.Object_80.geometry} material={materials.tennista_occhiblu} skeleton={nodes.Object_80.skeleton} />
                    <skinnedMesh name="Object_82" geometry={nodes.Object_82.geometry} material={materials.ponytail01} skeleton={nodes.Object_82.skeleton} />
                    <skinnedMesh name="Object_84" geometry={nodes.Object_84.geometry} material={materials.tennisdress} skeleton={nodes.Object_84.skeleton} />
                    <skinnedMesh name="Object_86" geometry={nodes.Object_86.geometry} material={materials.tennisracket} skeleton={nodes.Object_86.skeleton} />
                    <skinnedMesh name="Object_88" geometry={nodes.Object_88.geometry} material={materials.eyebrow001} skeleton={nodes.Object_88.skeleton} />
                    <skinnedMesh name="Object_90" geometry={nodes.Object_90.geometry} material={materials.sunvisor} skeleton={nodes.Object_90.skeleton} />
                    <skinnedMesh name="Object_92" geometry={nodes.Object_92.geometry} material={materials['low-poly']} skeleton={nodes.Object_92.skeleton} />
                    <skinnedMesh name="Object_94" geometry={nodes.Object_94.geometry} material={materials.eyelashes04} skeleton={nodes.Object_94.skeleton} />
                    <skinnedMesh name="Object_96" geometry={nodes.Object_96.geometry} material={materials.tennisshoes} skeleton={nodes.Object_96.skeleton} />
                  </group>
                </group>
                <group name="d" position={[-442.48, 1207.33, 226.54]} rotation={[-Math.PI / 2, 0, 0]} scale={20.49}>
                  <mesh name="d_M_255_255_255_255_0" geometry={nodes.d_M_255_255_255_255_0.geometry} material={materials.M_255_255_255_255} />
                </group>
                <group name="e" position={[-442.48, 1207.33, 226.54]} rotation={[-Math.PI / 2, 0, 0]} scale={20.49}>
                  <mesh name="e_M_255_255_102_211_0" geometry={nodes.e_M_255_255_102_211_0.geometry} material={materials.M_255_255_102_211} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tennisplayer.glb')
